export const COLOR_OF_APP_BOX = '#291F1D';
export const COLOR_OF_APP_BOX_BORDER = '#373737';

export const DEFAULT_MIN_WIDTH_OF_APP_BOX = 300;
export const DEFAULT_MIN_HEIGHT_OF_APP_BOX = 300;
export const DEFAULT_MAX_WIDTH_OF_APP_BOX = 1000;
export const DEFAULT_MAX_HEIGHT_OF_APP_BOX = 1000;
